apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: copy
  namespace: thisorthat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: copy
