apiVersion: v1
kind: Service
metadata:
  name: select-lb
  namespace: thisorthat
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote-label
  
